databases:
  - name: inventory_db
    databaseName: inventory_db
    user: inventory_db_user

services:
  - type: web
    name: inventory-management-system
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        fromDatabase:
          name: inventory_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: inventory_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory_db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: inventory_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventory_db
          property: port
